### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by guillemcordoba** [mvrahden/reinforce-js#1]
On the latest version, a new kind of error arises when trying to follow the example code on an angular project and causes the app to fail. The error disappears going back to an older version, e.g. 1.4.8

Complete console log: 
[log.txt](https://github.com/mvrahden/reinforce-js/files/1962406/log.txt)

Single component of the app:
[app.component.txt](https://github.com/mvrahden/reinforce-js/files/1962409/app.component.txt)

Let me know if I'm doing something wrong.

**Comment by mvrahden** [comment]
@guillemcordoba Was this related to the import-Error from the recurrent-js module?

Thanks for bringing this up!

**Comment by mvrahden** [comment]
I've update the dependency and published a new patch for npm.

Your sample code looks fine to me.

I'll mark the issue as solved. Should there be anything, please contact me.

Cheers!
